config/routes.rb
Rails.application.routes.draw do
  
  get '/' => 'welcome#index'

  root 'welcome#index'

  get '/contact' => 'welcome#contact'

  # get '/login' => 'welcome#login'

  # organization user ####################
  get '/organisations/login' => 'sessions#new'
  post '/organisations/login' => 'sessions#create'
  delete '/organisations/logout' => 'sessions#destroy'

  # organisation pages #####################
  get '/organisations' => 'organisations#index'
  get 'organisations/signup' => 'organisations#new'
  # show single organisation
  get '/organisations/:id' => 'organisations#show'
  
  resources :organisations

  # volunteer user ######################
  get '/volunteers/login' => 'volunteer_sessions#new'
  post '/volunteers/login' => 'volunteer_sessions#create'
  delete '/organisations/logout' => 'volunteer_sessions#destroy' #NEED TO CREATE THIS ELSE WHERE?


  # volunteer pages #####################
  get '/volunteers' => 'volunteers#index'
  get 'volunteers/signup' => 'volunteers#new'

  resources :volunteers

  resources :sessions

end

app/models/organisation.rb
class Organisation < ActiveRecord::Base
  has_secure_password
  has_many :proposals
end

app/models/proposal.rb
class Proposal < ActiveRecord::Base
  belongs_to :volunteer
  belongs_to :organisation
end

app/models/volunteer.rb
class Volunteer < ActiveRecord::Base
  has_secure_password
  has_many :proposals
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  helper_method :current_org
  
  def current_org
    Organisation.find(session[:organisation_id]) if session[:organisation_id]
  end
  
  def require_org 
    redirect_to '/organisations/login' unless current_org
  end
  
  def current_vol
    Volunteer.find(session[:volunteer_id]) if session[:volunteer_id]
  end
  
  def require_vol 
    redirect_to '/volunteers/login' unless current_vol
  end

end

app/controllers/organisations_controller.rb
class OrganisationsController < ApplicationController
  before_action :require_org, only:[:index, :show]

  def new
    @organisation = Organisation.new
  end

  def create
    @organisation = Organisation.new(organisation_params)
    if @organisation.save
      session[:organisation_id] = @organisation.id
      redirect_to '/'
    else
      redirect_to '/organisation/signup'
    end
  end

  def index
    @organisations = Organisation.all
  end

   def show
    @organisation = Organisation.find(params[:id])
    @props = @organisation.proposals
    @volunteers = []
    @current_org = current_org
    @props.each do |prop|
      @volunteers << prop.volunteer
    end
   end

  private
    def organisation_params
      params.require(:organisation).permit(:org_name, :first_name, :last_name, :email, :password)
    end  
end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController
  def new
  end
  def create
    @organisation = Organisation.find_by_email(params[:session][:email])
    if @organisation && @organisation.authenticate(params[:session][:password])
      session[:organisation_id] = @organisation.id
          
      redirect_to '/'
    else 
      @error = 'password or username wrong try again sucker'
      render :new
    end
  end
  
  def destroy
    session[:organisation_id] = nil
    redirect_to '/'
  end
  
end

app/controllers/volunteer_sessions_controller.rb
class VolunteerSessionsController < ApplicationController
  def new
  end

  def create
    
    @volunteer = Volunteer.find_by_email(params[:volunteer_session][:email])

    if @volunteer && @volunteer.authenticate(params[:volunteer_session][:password])
      session[:volunteer_id] = @volunteer.id
          
      redirect_to '/'
    else 
      @error = 'password or username wrong try again sucker'
      render :new
    end
  end
  
  def destroy
    session[:volunteer_id] = nil
    redirect_to '/'
  end
  
end

app/controllers/volunteers_controller.rb
class VolunteersController < ApplicationController
    def new
    @volunteer = Volunteer.new
    end

  def create
    @volunteer = Volunteer.new(volunteer_params)
    if @volunteer.save
      session[:volunteer_id] = @volunteer.id
      redirect_to '/'
    else
      redirect_to '/volunteer/signup'
    end
  end

  def index
    @volunteers = Volunteer.all
  end


  private
    def volunteer_params
      params.require(:volunteer).permit(:first_name, :last_name, :email, :password)
    end  
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end

  def contact
  end

  def login
  end

  def signup
  end
  
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/organisations_helper.rb
module OrganisationsHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/volunteers_helper.rb
module VolunteersHelper
end

app/helpers/welcome_helper.rb
module WelcomeHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <!-- Standard Meta -->
  <meta charset="utf-8" />
  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1" />
  <meta name="viewport" content="width=device-width, initial-scale=1.0, maximum-scale=1.0">

  <!-- Site Properties -->
  <title>Code Volunteers</title>
  <link rel="stylesheet" type="text/css" href="../dist/components/reset.css">
  <link rel="stylesheet" type="text/css" href="../dist/components/site.css">

  <link rel="stylesheet" type="text/css" href="../dist/components/container.css">
  <link rel="stylesheet" type="text/css" href="../dist/components/grid.css">
  <link rel="stylesheet" type="text/css" href="../dist/components/header.css">
  <link rel="stylesheet" type="text/css" href="../dist/components/image.css">
  <link rel="stylesheet" type="text/css" href="../dist/components/menu.css">

  <link rel="stylesheet" type="text/css" href="../dist/components/divider.css">
  <link rel="stylesheet" type="text/css" href="../dist/components/dropdown.css">
  <link rel="stylesheet" type="text/css" href="../dist/components/segment.css">
  <link rel="stylesheet" type="text/css" href="../dist/components/button.css">
  <link rel="stylesheet" type="text/css" href="../dist/components/list.css">
  <link rel="stylesheet" type="text/css" href="../dist/components/icon.css">
  <link rel="stylesheet" type="text/css" href="../dist/components/sidebar.css">
  <link rel="stylesheet" type="text/css" href="../dist/components/transition.css">

   <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>

  <script src="assets/library/jquery.min.js"></script>
  <script src="../dist/components/visibility.js"></script>
  <script src="../dist/components/sidebar.js"></script>
  <script src="../dist/components/transition.js"></script>
  <script>
  $(document)
    .ready(function() {

      // fix menu when passed
      $('.masthead')
        .visibility({
          once: false,
          onBottomPassed: function() {
            $('.fixed.menu').transition('fade in');
          },
          onBottomPassedReverse: function() {
            $('.fixed.menu').transition('fade out');
          }
        })
      ;

      // create sidebar and attach to menu open
      $('.ui.sidebar')
        .sidebar('attach events', '.toc.item')
      ;

    })
  ;
  </script>
</head>  

<%= yield %>

</body>
</html>

app/views/organisations/index.html.erb
<h1>Organisation Home </h1>

<h1>Organisations LISTICLE</h1>


<%@organisations.each do |org| %>

<h1><%= org.org_name %></h1>

<% end %>

app/views/organisations/new.html.erb
<h1>Organisation Sign up</h1>

    <%= form_for(@organisation) do |o| %>
       <%= o.text_field :org_name, :placeholder => "Organisation Name" %>
      <%= o.text_field :first_name, :placeholder => "First Name" %>
      <%= o.text_field :last_name, :placeholder => "Last Name" %>
      <%= o.email_field :email, :placeholder => "Email" %>
      <%= o.password_field :password, :placeholder => "Password" %>
      <%= o.submit "Create an account" %>
    <% end %>

app/views/organisations/show.html.erb
<% if @current_org && @current_org.id == @organisation.id %> 
  <p><%= @current_org.id %></p>
  <p>
    <%= link_to "Edit Organisation", edit_organisation_path(@organisation.id) %> 
  </p> 
<% end %>
<p>Org ID: <%= @organisation.id %></p>

<%= @organisation.org_name %>


<% @volunteers.each do |vol| %>
  <h3><%= vol.first_name %></h3>

<% end %>

<% @props.each do |prop| %>
  <%= prop.volunteer.first_name %>
  <%= prop.status %>

<% end %>

app/views/users/index.html.erb
<h1>uuusers are losers</h1>


<%@users.each do |user| %>

<h1><%= user.name %></h1>

<% end %>

app/views/volunteer_sessions/new.html.erb
<!-- THIS IS THE ORGANISATIONS SIGN UP FORM -->

<!-- Following Menu -->
<div class="ui large top fixed hidden menu">
  <div class="ui container">
    <a class="active item" href="/">Coder Volunteer</a>
    <a class="item" href="/organisations">Organisations</a>
    <a class="item" href="/volunteers">Volunteers</a>
    <div class="right menu">
      <div class="item"><% if current_org %>
      <%= current_org.email %>
      </div>
      <div class="item">
        <form action="/organisations/logout" method="post">
          <input type="hidden" value="delete" name="_method">
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <button class="ui button">Logout</button>
        </form>
          <% end %>
      </div>
    </div>
  </div>
</div>

<!-- Sidebar Menu -->
<div class="ui vertical inverted sidebar menu">
  <a class="active item" href="/">Code Volunteers</a>
  <a class="item" href="/organisations">Organisations</a>
  <a class="item" href="volunteers">Volunteers</a>
  <div class="item"><% if current_org %>
      <%= current_org.email %>
      </div>
      <div class="item">
        <form action="/organisations/logout" method="post">
          <input type="hidden" value="delete" name="_method">
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <button class="ui button">Logout</button>
        </form>
          <% end %>
      </div>
</div>

<!-- Page Contents -->
<div class="pusher">
  <div class="ui inverted vertical masthead center aligned segment login"> 

    <div class="ui container">
      <div class="ui large secondary inverted pointing menu">
        <a class="toc item">
          <i class="sidebar icon"></i>
        </a>
        <a class="active item" href="/">Code Volunteers</a>
        <a class="item" href="/organisations">Organisations</a>
        <a class="item" href='/volunteers'>Volunteers</a>
        <div class="right item">
          <% if current_org %>
      <%= current_org.email %>
      <form action="/organisations/logout" method="post">
          <input type="hidden" value="delete" name="_method">
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <button class="ui button">Logout</button>
        </form>
          <% end %>
        </div>
      </div>
    </div>

  <script>
  $(document)
    .ready(function() {
      $('.ui.form')
        .form({
          fields: {
            email: {
              identifier  : 'session[email]',
              rules: [
                {
                  type   : 'empty',
                  prompt : 'Please enter your e-mail'
                },
                {
                  type   : 'email',
                  prompt : 'Please enter a valid e-mail'
                }
              ]
            },
            password: {
              identifier  : 'session[password]',
              rules: [
                {
                  type   : 'empty',
                  prompt : 'Please enter your password'
                },
                {
                  type   : 'length[3]',
                  prompt : 'Your password must be at least 3 characters'
                }
              ]
            }
          }
        })
      ;
    })
  ;
  </script>


<div class="ui middle aligned center aligned grid">
  <div class="column">
    <h2 class="ui teal image header">
      <div class="content">
        <h1>Volunteer Login</h1>
      </div>
    </h2>
       <form action="/volunteers/login" accept-charset="UTF-8" method="post" class="ui large form">
     <input name="utf8" type="hidden" value="✓">
    <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
    <input type="hidden" name="authenticity_token" value="">
      <div class="ui stacked segment">
        <div class="field">
          <div class="ui left icon input">
            <i class="user icon"></i>
            <input placeholder="Email" type="email" name="volunteer_session[email]" id="session_email"> 
          </div>
        </div>
        <div class="field">
          <div class="ui left icon input">
            <i class="lock icon"></i>
            <input placeholder="Password" type="password" name="volunteer_session[password]" id="session_password">
          </div>
        </div>
        <input type="submit" name="commit" value="Log in" class="ui fluid large teal submit button">
      </div>

      <div class="ui error message"></div>

    </form>

    <div class="ui message">
      New to us? <a href="/volunteers/signup">Sign Up</a>
    </div>
  </div>
</div>

</div>

app/views/volunteers/index.html.erb
<h1> Volunteers Home Page </h1>

<%@volunteers.each do |vol| %>

<h1><%= vol.first_name %></h1>

<% end %>

app/views/volunteers/new.html.erb
<h1>VOLUNTEER Sign up</h1>

    <%= form_for(@volunteer) do |o| %>
      <%= o.text_field :first_name, :placeholder => "First Name" %>
      <%= o.text_field :last_name, :placeholder => "Last Name" %>
      <%= o.email_field :email, :placeholder => "Email" %>
      <%= o.password_field :password, :placeholder => "Password" %>
      <%= o.submit "Create an account" %>
    <% end %>

app/views/welcome/contact.html.erb
<h1>Get in touchizzle</h1>

app/views/welcome/index.html.erb
<!-- Following Menu -->
<div class="ui large top fixed hidden menu">
  <div class="ui container">
    <a class="active item" href="/">Coder Volunteer</a>
    <a class="item" href="/organisations">Organisations</a>
    <a class="item" href="/volunteers">Volunteers</a>
    <div class="right menu">
      <div class="item"><% if current_org %>
      <%= current_org.email %>
      </div>
      <div class="item">
        <form action="/organisations/logout" method="post">
          <input type="hidden" value="delete" name="_method">
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <button class="ui button">Logout</button>
        </form>
          <% end %>
      </div>
    </div>
  </div>
</div>


<!-- Sidebar Menu -->
<div class="ui vertical inverted sidebar menu">
  <a class="active item" href="/">Code Volunteers</a>
  <a class="item" href="/organisations">Organisations</a>
  <a class="item" href="volunteers">Volunteers</a>
  <div class="item"><% if current_org %>
      <%= current_org.email %>
      </div>
      <div class="item">
        <form action="/organisations/logout" method="post">
          <input type="hidden" value="delete" name="_method">
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <button class="ui button">Logout</button>
        </form>
          <% end %>
      </div>
</div>


<!-- Page Contents -->
<div class="pusher">
  <div class="ui inverted vertical masthead center aligned segment">

    <div class="ui container">
      <div class="ui large secondary inverted pointing menu">
        <a class="toc item">
          <i class="sidebar icon"></i>
        </a>
        <a class="active item" href="/">Code Volunteers</a>
        <a class="item" href="/organisations">Organisations</a>
        <a class="item" href='/volunteers'>Volunteers</a>
        <div class="right item">
          <% if current_org %>
      <%= current_org.email %>
      <form action="/organisations/logout" method="post">
          <input type="hidden" value="delete" name="_method">
          <%= hidden_field_tag :authenticity_token, form_authenticity_token %>
          <button class="ui button">Logout</button>
        </form>
          <% end %>

        </div>
      </div>
    </div>

    <div class="ui text container">
      <h1 class="ui inverted header">
        Volunteer Teaching Coding Abroad
      </h1>
      <h2>Breaking the cycle of poverty through education.</h2>
    </div>

  </div>

  <div class="ui vertical stripe segment">
    <div class="ui middle aligned stackable grid container">
      <div class="row">
        <div class="eight wide column">
          <h3 class="ui header">We Help Communities Grow</h3>
          <p>We want to educate the disadvantaged in a evergreen skill set that will break the cycle of poverty.</p>
          <h3 class="ui header">Experience Culture While Coding</h3>
          <p>Volunteers can use their skill set to teach computing and coding around the world. Combine your holiday with unforgettable experiences and people.</p>
        </div>
        <div class="six wide right floated column">
          <img src="http://i.imgbox.com/jkrc7gIH.png" class="ui large bordered rounded image">
        </div>
      </div>
    </div>
  </div>


  <div class="ui vertical stripe quote segment">
    <div class="ui equal width stackable internally celled grid">
      <div class="center aligned row">
        <div class="column">
          <h3>Organisations</h3>
          <p>Get skilled volunteers to run a capsule program, teach skills that will break teh cycle of poverty and allow your community to enter a global economy.</p>
            <div class="row">
              <a class="ui huge button" href="organisations/signup">Organisation Sign Up</a>
            </div>
        </div>
        <div class="column">
          <h3>Volunteers</h3>
          <p>
            Use your skills to enrich the lives of others, while being a part of a community and travelling the world. Create a capsule project and take the lead in the education of others.
          </p>
          <div class="row">
            <a class="ui huge button" href="volunteers/signup">Volunteer Sign Up</a>
            </div>
        </div>
        </div>
      </div>
    </div>


  <div class="ui inverted vertical footer segment">
    <div class="ui container">
      <div class="ui stackable inverted divided equal height stackable grid">
        <div class="three wide column">
          <h4 class="ui inverted header">Organisations</h4>
          <div class="ui inverted link list">
            <a href="/organisations/signup" class="item">Sign Up</a>
            <a href="/organisations/login" class="item">Login</a>
            <a href="/organisations/faqs" class="item">FAQs</a>
            <a href="/organisations" class="item">Browse All</a>
          </div>
        </div>
        <div class="three wide column">
          <h4 class="ui inverted header">Volunteers</h4>
          <div class="ui inverted link list">
            <a href="/volunteers/signup" class="item">Sign Up</a>
            <a href="/volunteers/login" class="item">Login</a>
            <a href="/volunteers/faqs" class="item">FAQs</a>
            <a href="/volunteers/testimonials" class="item">Testimonials</a>
          </div>
        </div>
        <div class="seven wide column">
          <h4 class="ui inverted header">Our Mission</h4>
          <p>Breaking the cycle of poverty through current and continuious education.</p>
        </div>
      </div>
    </div>
  </div>
</div>

app/views/welcome/signup.html.erb
<h1>sign up</h1>

<div class="ui top attached tabular menu">
  <a class="active item" data-tab="first">Volunteer</a>
  <a class="item" data-tab="second">Organisation</a>
</div>
<div class="ui bottom attached active tab segment" data-tab="first">
  First
</div>
<div class="ui bottom attached tab segment" data-tab="second">
  <form class="ui form">
  <h4 class="ui dividing header">Shipping Information</h4>
  <div class="field">
    <label>Name</label>
    <div class="two fields">
      <div class="field">
        <input type="text" name="shipping[first-name]" placeholder="First Name">
      </div>
      <div class="field">
        <input type="text" name="shipping[last-name]" placeholder="Last Name">
      </div>
    </div>
  </div>
  <div class="field">
    <label>Billing Address</label>
    <div class="fields">
      <div class="twelve wide field">
        <input type="text" name="shipping[address]" placeholder="Street Address">
      </div>
      <div class="four wide field">
        <input type="text" name="shipping[address-2]" placeholder="Apt #">
      </div>
    </div>
  </div>
  <div class="two fields">
    <div class="field">
      <label>State</label><input type="text" name="state" placeholder="State">
    </div>
    <div class="field">
      <label>Country</label>
      <div class="ui fluid search selection dropdown">
        <input type="hidden" name="country">
        <i class="dropdown icon"></i>
        <div class="default text">Select Country</div>
        <div class="menu">
    <div class="item" data-value="af"><i class="af flag"></i>Afghanistan</div>
    <div class="item" data-value="ax"><i class="ax flag"></i>Aland Islands</div>
    <div class="item" data-value="al"><i class="al flag"></i>Albania</div>
    <div class="item" data-value="dz"><i class="dz flag"></i>Algeria</div>
    <div class="item" data-value="as"><i class="as flag"></i>American Samoa</div>
    <div class="item" data-value="ad"><i class="ad flag"></i>Andorra</div>
    <div class="item" data-value="ao"><i class="ao flag"></i>Angola</div>
    <div class="item" data-value="ai"><i class="ai flag"></i>Anguilla</div>
    <div class="item" data-value="ag"><i class="ag flag"></i>Antigua</div>
    <div class="item" data-value="ar"><i class="ar flag"></i>Argentina</div>
    <div class="item" data-value="am"><i class="am flag"></i>Armenia</div>
    <div class="item" data-value="aw"><i class="aw flag"></i>Aruba</div>
    <div class="item" data-value="au"><i class="au flag"></i>Australia</div>
    <div class="item" data-value="at"><i class="at flag"></i>Austria</div>
    <div class="item" data-value="az"><i class="az flag"></i>Azerbaijan</div>
  </div>
      </div>
    </div>
  </div>
  <h4 class="ui dividing header">Billing Information</h4>
  <div class="field">
    <label>Card Type</label>
    <div class="ui selection dropdown">
      <input type="hidden" name="card[type]">
      <div class="default text">Type</div>
      <i class="dropdown icon"></i>
      <div class="menu">
        <div class="item" data-value="visa">
          <i class="visa icon"></i>
          Visa
        </div>
        <div class="item" data-value="amex">
          <i class="amex icon"></i>
          American Express
        </div>
        <div class="item" data-value="discover">
          <i class="discover icon"></i>
          Discover
        </div>
      </div>
    </div>
  </div>
  <div class="fields">
    <div class="seven wide field">
      <label>Card Number</label>
      <input type="text" name="card[number]" maxlength="16" placeholder="Card #">
    </div>
    <div class="three wide field">
      <label>CVC</label>
      <input type="text" name="card[cvc]" maxlength="3" placeholder="CVC">
    </div>
    <div class="six wide field">
      <label>Expiration</label>
      <div class="two fields">
        <div class="field">
          <select class="ui fluid search dropdown" name="card[expire-month]">
            <option value="">Month</option>
            <option value="1">January</option>
            <option value="2">February</option>
            <option value="3">March</option>
            <option value="4">April</option>
            <option value="5">May</option>
            <option value="6">June</option>
            <option value="7">July</option>
            <option value="8">August</option>
            <option value="9">September</option>
            <option value="10">October</option>
            <option value="11">November</option>
            <option value="12">December</option>
          </select>
        </div>
        <div class="field">
          <input type="text" name="card[expire-year]" maxlength="4" placeholder="Year">
        </div>
      </div>
    </div>
  </div>
   <h4 class="ui dividing header">Receipt</h4>
   <div class="field">
    <label>Send Receipt To:</label>
    <div class="ui fluid multiple search selection dropdown">
      <input type="hidden" name="receipt">
      <i class="dropdown icon"></i>
      <div class="default text">Saved Contacts</div>
      <div class="menu">
        <div class="item" data-value="jenny" data-text="Jenny">
          <img class="ui mini avatar image" src="/images/avatar/small/jenny.jpg">
          Jenny Hess
        </div>
        <div class="item" data-value="elliot" data-text="Elliot">
          <img class="ui mini avatar image" src="/images/avatar/small/elliot.jpg">
          Elliot Fu
        </div>
        <div class="item" data-value="stevie" data-text="Stevie">
          <img class="ui mini avatar image" src="/images/avatar/small/stevie.jpg">
          Stevie Feliciano
        </div>
        <div class="item" data-value="christian" data-text="Christian">
          <img class="ui mini avatar image" src="/images/avatar/small/christian.jpg">
          Christian
        </div>
        <div class="item" data-value="matt" data-text="Matt">
          <img class="ui mini avatar image" src="/images/avatar/small/matt.jpg">
          Matt
        </div>
        <div class="item" data-value="justen" data-text="Justen">
          <img class="ui mini avatar image" src="/images/avatar/small/justen.jpg">
          Justen Kitsune
        </div>
      </div>
    </div>
  </div>
   <div class="ui segment">
    <div class="field">
      <div class="ui toggle checkbox">
        <input type="checkbox" name="gift" tabindex="0" class="hidden">
        <label>Do not include a receipt in the package</label>
      </div>
    </div>
  </div>
  <div class="ui button" tabindex="0">Submit Order</div>
</form>
</div>

<script>$('.menu .item')
  .tab()
;</script>
<!-- Do i need to put this in on this page when I already have it somewhere else? -->